# Generated by Django 3.2.6 on 2022-07-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blugz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='aaadmin', max_length=255),
        ),
    ]
